# Puerto dinámico asignado por Azure
server.port=${PORT:8080}

# Conexión a la base de datos Supabase
spring.datasource.url=jdbc:postgresql://db.xayrocnzgkjldikgxdgl.supabase.co:5432/postgres
spring.datasource.username=${DB_USER_SUPABASE}  # Definido en Azure App Service
spring.datasource.password=${DB_PWD_SUPABASE}   # Definido en Azure App Service
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false
